
#ifndef CMAKE_GOOGLETEST_PYBIND11_EXAMPLE_FACTORIALLIB_H
#define CMAKE_GOOGLETEST_PYBIND11_EXAMPLE_FACTORIALLIB_H

namespace myfactorial {


    double factorial(int n);

}

#endif //CMAKE_GOOGLETEST_PYBIND11_EXAMPLE_FACTORIALLIB_H
